vich_uploader:
    db_driver: orm
    mappings:
        property_image:
            uri_prefix: /images/properties
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public/images/properties'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
